---
ansible_user: Administrator
ansible_password: "{{ lookup('env', 'HYPERV_PASSWORD') }}"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_winrm_read_timeout_sec: 300
ansible_winrm_operation_timeout_sec: 290
