---
- name: Configure appliance(s)
  hosts: platforms_vyos
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH reachability
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 15
        timeout: 300

  roles:
    - vyos_common
    - vyos_firewall
    - role: vyos_edge_router
      when: vyos.role == 'edge_router'
    - role: vyos_dual_wan
      when: vyos.dual_wan | default(false)
    - role: vyos_ipsec_vpn
      when: vyos.ipsec_vpn is defined
    - role: vyos_ha
      when: vyos.ha_pair | default(false)